/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppsSlugRouteImport } from './routes/_authenticated/apps/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_authenticated/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppsSlugRoute = AuthenticatedAppsSlugRouteImport.update({
  id: '/_authenticated/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/apps/$slug': typeof AuthenticatedAppsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/apps/$slug': typeof AuthenticatedAppsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/apps/$slug': typeof AuthenticatedAppsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/apps/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/apps/$slug'
  id: '__root__' | '/' | '/_authenticated/admin' | '/_authenticated/apps/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppsSlugRoute: typeof AuthenticatedAppsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/apps/$slug': {
      id: '/_authenticated/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AuthenticatedAppsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppsSlugRoute: AuthenticatedAppsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
