/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppsSlugRouteImport } from './routes/_authenticated/apps/$slug'
import { Route as ApiPublicHooksSyncAgilePricesRouteImport } from './routes/api/public/hooks/sync-agile-prices'
import { Route as ApiPublicHooksRunDueIngestionsRouteImport } from './routes/api/public/hooks/run-due-ingestions'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsSlugRoute = AuthenticatedAppsSlugRouteImport.update({
  id: '/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksSyncAgilePricesRoute =
  ApiPublicHooksSyncAgilePricesRouteImport.update({
    id: '/api/public/hooks/sync-agile-prices',
    path: '/api/public/hooks/sync-agile-prices',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunDueIngestionsRoute =
  ApiPublicHooksRunDueIngestionsRouteImport.update({
    id: '/api/public/hooks/run-due-ingestions',
    path: '/api/public/hooks/run-due-ingestions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/users': typeof AuthenticatedUsersRoute
  '/apps/$slug': typeof AuthenticatedAppsSlugRoute
  '/api/public/hooks/run-due-ingestions': typeof ApiPublicHooksRunDueIngestionsRoute
  '/api/public/hooks/sync-agile-prices': typeof ApiPublicHooksSyncAgilePricesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/users': typeof AuthenticatedUsersRoute
  '/apps/$slug': typeof AuthenticatedAppsSlugRoute
  '/api/public/hooks/run-due-ingestions': typeof ApiPublicHooksRunDueIngestionsRoute
  '/api/public/hooks/sync-agile-prices': typeof ApiPublicHooksSyncAgilePricesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/apps/$slug': typeof AuthenticatedAppsSlugRoute
  '/api/public/hooks/run-due-ingestions': typeof ApiPublicHooksRunDueIngestionsRoute
  '/api/public/hooks/sync-agile-prices': typeof ApiPublicHooksSyncAgilePricesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/users'
    | '/apps/$slug'
    | '/api/public/hooks/run-due-ingestions'
    | '/api/public/hooks/sync-agile-prices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/users'
    | '/apps/$slug'
    | '/api/public/hooks/run-due-ingestions'
    | '/api/public/hooks/sync-agile-prices'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/users'
    | '/_authenticated/apps/$slug'
    | '/api/public/hooks/run-due-ingestions'
    | '/api/public/hooks/sync-agile-prices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksRunDueIngestionsRoute: typeof ApiPublicHooksRunDueIngestionsRoute
  ApiPublicHooksSyncAgilePricesRoute: typeof ApiPublicHooksSyncAgilePricesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/$slug': {
      id: '/_authenticated/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AuthenticatedAppsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/sync-agile-prices': {
      id: '/api/public/hooks/sync-agile-prices'
      path: '/api/public/hooks/sync-agile-prices'
      fullPath: '/api/public/hooks/sync-agile-prices'
      preLoaderRoute: typeof ApiPublicHooksSyncAgilePricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-due-ingestions': {
      id: '/api/public/hooks/run-due-ingestions'
      path: '/api/public/hooks/run-due-ingestions'
      fullPath: '/api/public/hooks/run-due-ingestions'
      preLoaderRoute: typeof ApiPublicHooksRunDueIngestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedAppsSlugRoute: typeof AuthenticatedAppsSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedAppsSlugRoute: AuthenticatedAppsSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksRunDueIngestionsRoute: ApiPublicHooksRunDueIngestionsRoute,
  ApiPublicHooksSyncAgilePricesRoute: ApiPublicHooksSyncAgilePricesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
